"""add trip_photos table

Revision ID: 45b3564142eb
Revises: 5f77ae6a29a7
Create Date: 2026-03-16 15:32:11.029499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b3564142eb'
down_revision = '5f77ae6a29a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_photos',
    sa.Column('pict_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('pict_name', sa.String(length=255), nullable=False),
    sa.Column('pict_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pict_small_url', sa.String(length=1024), nullable=True),
    sa.Column('pict_origin_url', sa.String(length=1024), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pict_id')
    )
    with op.batch_alter_table('trip_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_photos_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_photos_trip_id'))

    op.drop_table('trip_photos')
    # ### end Alembic commands ###
