"""-m

Revision ID: 5f77ae6a29a7
Revises: 8a213da62684
Create Date: 2026-03-15 16:02:03.659916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f77ae6a29a7'
down_revision = '8a213da62684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_seq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_location_from', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('plan_loc_frm_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plan_loc_frm_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plan_location_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('plan_loc_to_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plan_loc_to_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_plans', schema=None) as batch_op:
        batch_op.drop_column('plan_loc_to_longitude')
        batch_op.drop_column('plan_loc_to_latitude')
        batch_op.drop_column('plan_location_to')
        batch_op.drop_column('plan_loc_frm_longitude')
        batch_op.drop_column('plan_loc_frm_latitude')
        batch_op.drop_column('plan_location_from')
        batch_op.drop_column('plan_seq')

    # ### end Alembic commands ###
