"""-m

Revision ID: 8a213da62684
Revises: 
Create Date: 2026-03-15 15:51:10.345844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a213da62684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('plan_time', sa.String(length=10), nullable=True),
    sa.Column('plan_activity', sa.String(length=500), nullable=False),
    sa.Column('plan_traffic', sa.String(length=255), nullable=True),
    sa.Column('plan_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_plans_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_plans_trip_id'), ['trip_id'], unique=False)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('itinerary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary', sa.TEXT(), nullable=True))

    with op.batch_alter_table('trip_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_plans_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_plans_activity_id'))

    op.drop_table('trip_plans')
    # ### end Alembic commands ###
