"""add minio fields to users and access_flag to trip_photos

Revision ID: 9123b4450313
Revises: 45b3564142eb
Create Date: 2026-03-16 15:48:39.447332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9123b4450313'
down_revision = '45b3564142eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_flag', sa.SmallInteger(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minio_access_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('minio_secret_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('minio_bucket', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('minio_bucket')
        batch_op.drop_column('minio_secret_key')
        batch_op.drop_column('minio_access_key')

    with op.batch_alter_table('trip_photos', schema=None) as batch_op:
        batch_op.drop_column('access_flag')

    # ### end Alembic commands ###
