"""add pict_size_kb to trip_photos

Revision ID: f9f2eb96b47b
Revises: 9123b4450313
Create Date: 2026-03-16 16:22:11.893538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9f2eb96b47b'
down_revision = '9123b4450313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # pict_size_kb already exists in trip_photos (added by a prior partial run)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_cloud_storage_quota', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False, server_default='5242880'))
        batch_op.add_column(sa.Column('user_storage_usage', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_storage_usage')
        batch_op.drop_column('user_cloud_storage_quota')

    with op.batch_alter_table('trip_photos', schema=None) as batch_op:
        batch_op.drop_column('pict_size_kb')

    # ### end Alembic commands ###
